---
on: [push]

jobs:
  bump-version:
    name: increament version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # - name: increment tag
      #   id: increment-tag
      #   uses: vishnuatrai-labs/increment-git-tag@main
      #   with:
      #     version-type: patch

      # - name: get the new version
      #   run: echo "New version is available ${{ steps.increment-tag.outputs.new-version }}"

      - name: generate artifact file
        run: mkdir -p artifacts_files && echo "Generating artifact files" >> artifacts_files/test.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: samples artifact files
          path: artifacts_files

      - name: download artifacts 
        uses: actions/download-artifact@v3
        with:
          name: samples artifact files

      - name: test artifact
        run: ls -R
